packages:
  - backend
  - frontend

allowBuilds:
  bcrypt: true
  esbuild: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

overrides:
  rollup: ^4.59.0
  qs: ^6.15.2
  uuid: ^11.1.1
strictDepBuilds: true
