import { useFacturaDetalleData } from './facturaDetalle/useFacturaDetalleData.js';
import { useFacturaDetalleActions } from './facturaDetalle/useFacturaDetalleActions.js';

export const useFacturaDetalle = ({ id, sociedadId, dataDependencies, actionDependencies }) => {
  const data = useFacturaDetalleData({ id, sociedadId, dependencies: dataDependencies });

  const actions = useFacturaDetalleActions({
    id,
    factura: data.factura,
    conta: data.conta,
    proveedoresSociedad: data.proveedoresSociedad,
    tablaPagoActual: data.tablaPagoActual,
    notaCreditoActual: data.notaCreditoActual,
    commentUser: data.commentUser,
    commentText: data.commentText,
    estadoNuevo: data.estadoNuevo,
    estadoUser: data.estadoUser,
    estadoMotivo: data.estadoMotivo,
    retencionPagoMonto: data.retencionPagoMonto,
    retencionPagoFecha: data.retencionPagoFecha,
    retencionPagoNotas: data.retencionPagoNotas,
    fetchAll: data.fetchAll,
    setComentarios: data.setComentarios,
    setCommentText: data.setCommentText,
    setEstadoMotivo: data.setEstadoMotivo,
    setEstadoNuevo: data.setEstadoNuevo,
    setConta: data.setConta,
    setContaSaving: data.setContaSaving,
    setContaMessage: data.setContaMessage,
    setContaError: data.setContaError,
    setTablasPagoProveedor: data.setTablasPagoProveedor,
    setTablaPagoActual: data.setTablaPagoActual,
    setTablasModalOpen: data.setTablasModalOpen,
    setTablasError: data.setTablasError,
    setTablasLoading: data.setTablasLoading,
    setNotasCreditoProveedor: data.setNotasCreditoProveedor,
    setNotaCreditoActual: data.setNotaCreditoActual,
    setNotasModalOpen: data.setNotasModalOpen,
    setNotasError: data.setNotasError,
    setNotasLoading: data.setNotasLoading,
    setRetencionPagoMonto: data.setRetencionPagoMonto,
    setRetencionPagoNotas: data.setRetencionPagoNotas,
    setRetencionPagoSaving: data.setRetencionPagoSaving,
    setRetencionPagoError: data.setRetencionPagoError,
    setRetencionPagoMessage: data.setRetencionPagoMessage,
    setMhLoading: data.setMhLoading,
    setMhError: data.setMhError,
    dependencies: actionDependencies
  });

  return {
    factura: data.factura,
    comentarios: data.comentarios,
    estados: data.estados,
    loading: data.loading,
    commentUser: data.commentUser,
    setCommentUser: data.setCommentUser,
    commentText: data.commentText,
    setCommentText: data.setCommentText,
    estadoNuevo: data.estadoNuevo,
    setEstadoNuevo: data.setEstadoNuevo,
    estadoUser: data.estadoUser,
    setEstadoUser: data.setEstadoUser,
    estadoMotivo: data.estadoMotivo,
    setEstadoMotivo: data.setEstadoMotivo,
    error: data.error,
    mhLoading: data.mhLoading,
    mhError: data.mhError,
    conta: data.conta,
    proveedoresSociedad: data.proveedoresSociedad,
    tablasPagoProveedor: data.tablasPagoProveedor,
    tablaPagoActual: data.tablaPagoActual,
    tablasModalOpen: data.tablasModalOpen,
    setTablasModalOpen: data.setTablasModalOpen,
    tablasLoading: data.tablasLoading,
    tablasError: data.tablasError,
    notasCreditoProveedor: data.notasCreditoProveedor,
    notaCreditoActual: data.notaCreditoActual,
    notasModalOpen: data.notasModalOpen,
    setNotasModalOpen: data.setNotasModalOpen,
    notasLoading: data.notasLoading,
    notasError: data.notasError,
    retencionPagos: data.retencionPagos,
    contaSaving: data.contaSaving,
    contaMessage: data.contaMessage,
    contaError: data.contaError,
    retencionPagoMonto: data.retencionPagoMonto,
    setRetencionPagoMonto: data.setRetencionPagoMonto,
    retencionPagoFecha: data.retencionPagoFecha,
    setRetencionPagoFecha: data.setRetencionPagoFecha,
    retencionPagoNotas: data.retencionPagoNotas,
    setRetencionPagoNotas: data.setRetencionPagoNotas,
    retencionPagoSaving: data.retencionPagoSaving,
    retencionPagoError: data.retencionPagoError,
    retencionPagoMessage: data.retencionPagoMessage,
    addComment: actions.addComment,
    changeEstado: actions.changeEstado,
    handleContaChange: actions.handleContaChange,
    abrirAsociarTablaPago: actions.abrirAsociarTablaPago,
    asociarTablaPago: actions.asociarTablaPago,
    abrirAsociarNotaCredito: actions.abrirAsociarNotaCredito,
    asociarNotaCredito: actions.asociarNotaCredito,
    verTablaPagoAsociada: actions.verTablaPagoAsociada,
    verNotaCreditoAsociada: actions.verNotaCreditoAsociada,
    guardarContabilizacion: actions.guardarContabilizacion,
    registrarPagoRetencion: actions.registrarPagoRetencion,
    verMensajeHacienda: actions.verMensajeHacienda,
    verManifest: actions.verManifest
  };
};
