-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auditoria
(
    id serial NOT NULL,
    factura_id integer NOT NULL,
    accion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    detalles jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auditoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comentarios_documento
(
    id serial NOT NULL,
    factura_id integer NOT NULL,
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    texto text COLLATE pg_catalog."default" NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comentarios_documento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estados_documento
(
    id serial NOT NULL,
    factura_id integer NOT NULL,
    estado_anterior character varying(50) COLLATE pg_catalog."default",
    estado_nuevo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    motivo text COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT estados_documento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facturas
(
    id serial NOT NULL,
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    consecutivo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_emision timestamp without time zone,
    emisor jsonb NOT NULL,
    receptor jsonb NOT NULL,
    resumen jsonb NOT NULL,
    xml_completo jsonb NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ruta_archivo character varying(255) COLLATE pg_catalog."default",
    ruta_pdf character varying(255) COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default" DEFAULT 'no_contabilizado'::character varying,
    sociedad_id integer NOT NULL,
    ruta_xml character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT facturas_pkey PRIMARY KEY (id),
    CONSTRAINT facturas_clave_key UNIQUE (clave)
);

CREATE TABLE IF NOT EXISTS public.facturas_contabilizacion
(
    id serial NOT NULL,
    factura_id integer NOT NULL,
    fecha_documento date,
    fecha_vencimiento date,
    fecha_contabilizacion date DEFAULT CURRENT_DATE,
    plazo_credito integer,
    retencion numeric(18, 4),
    descuento numeric(18, 4),
    anticipo_aplicado numeric(18, 4),
    centro_costo character varying(100) COLLATE pg_catalog."default",
    cuenta_contable character varying(100) COLLATE pg_catalog."default",
    proyecto character varying(150) COLLATE pg_catalog."default",
    orden_compra character varying(100) COLLATE pg_catalog."default",
    numero_proveedor character varying(50) COLLATE pg_catalog."default",
    notas text COLLATE pg_catalog."default",
    metadata jsonb,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT facturas_contabilizacion_pkey PRIMARY KEY (id),
    CONSTRAINT facturas_contabilizacion_factura_id_key UNIQUE (factura_id)
);

CREATE TABLE IF NOT EXISTS public.mensajes_hacienda
(
    id serial NOT NULL,
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mensaje smallint,
    estado character varying(50) COLLATE pg_catalog."default",
    detalle text COLLATE pg_catalog."default",
    xml_completo jsonb NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sociedad_id integer NOT NULL,
    ruta_xml character varying(255) COLLATE pg_catalog."default",
    factura_id integer,
    CONSTRAINT mensajes_hacienda_pkey PRIMARY KEY (id),
    CONSTRAINT mensajes_hacienda_clave_key UNIQUE (clave),
    CONSTRAINT mensajes_hacienda_mensaje_check CHECK (mensaje IN (1,2,3))
);

CREATE TABLE IF NOT EXISTS public.notas_credito
(
    id serial NOT NULL,
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_emision timestamp without time zone,
    factura_id integer,
    referencia jsonb NOT NULL,
    xml_completo jsonb NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ruta_archivo character varying(255) COLLATE pg_catalog."default",
    ruta_pdf character varying(255) COLLATE pg_catalog."default",
    sociedad_id integer NOT NULL,
    ruta_xml character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT notas_credito_pkey PRIMARY KEY (id),
    CONSTRAINT notas_credito_clave_key UNIQUE (clave)
);

CREATE TABLE IF NOT EXISTS public.permisos
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permisos_pkey PRIMARY KEY (id),
    CONSTRAINT permisos_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    nivel_jerarquia integer DEFAULT 0,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    codigo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_codigo_key UNIQUE (codigo),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.roles_permisos
(
    id serial NOT NULL,
    rol_id integer NOT NULL,
    permiso_id integer NOT NULL,
    CONSTRAINT roles_permisos_pkey PRIMARY KEY (id),
    CONSTRAINT roles_permisos_rol_id_permiso_id_key UNIQUE (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS public.sociedades
(
    id serial NOT NULL,
    codigo character varying(20) COLLATE pg_catalog."default",
    nombre_proyecto character varying(150) COLLATE pg_catalog."default",
    razon_social character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cedula_juridica character varying(20) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sociedades_pkey PRIMARY KEY (id),
    CONSTRAINT sociedades_cedula_juridica_key UNIQUE (cedula_juridica),
    CONSTRAINT sociedades_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.tramites_pago
(
    id serial NOT NULL,
    sociedad_id integer,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'en_aprobacion_gerencia'::character varying,
    creado_por character varying(100) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tramites_pago_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tramites_pago_documentos
(
    id serial NOT NULL,
    tramite_id integer NOT NULL,
    factura_id integer NOT NULL,
    estado_gerencia character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    estado_gerencia_contable character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    estado_financiero character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    motivo_gerencia text COLLATE pg_catalog."default",
    motivo_gerencia_contable text COLLATE pg_catalog."default",
    motivo_financiero text COLLATE pg_catalog."default",
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado_tesoreria character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    motivo_tesoreria text COLLATE pg_catalog."default",
    CONSTRAINT tramites_pago_documentos_pkey PRIMARY KEY (id),
    CONSTRAINT tramites_pago_documentos_tramite_id_factura_id_key UNIQUE (tramite_id, factura_id)
);

CREATE TABLE IF NOT EXISTS public.tramites_pago_historial
(
    id serial NOT NULL,
    tramite_id integer NOT NULL,
    factura_id integer,
    accion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado_anterior character varying(50) COLLATE pg_catalog."default",
    estado_nuevo character varying(50) COLLATE pg_catalog."default",
    usuario character varying(100) COLLATE pg_catalog."default",
    motivo text COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tramites_pago_historial_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol_id integer NOT NULL,
    activo boolean DEFAULT true,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.versiones_documento
(
    id serial NOT NULL,
    factura_id integer NOT NULL,
    numero integer NOT NULL,
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cambios text COLLATE pg_catalog."default",
    ruta_archivo character varying(255) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT versiones_documento_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.auditoria
    ADD CONSTRAINT auditoria_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auditoria_factura
    ON public.auditoria(factura_id);


ALTER TABLE IF EXISTS public.comentarios_documento
    ADD CONSTRAINT comentarios_documento_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_comentarios_factura
    ON public.comentarios_documento(factura_id);


ALTER TABLE IF EXISTS public.estados_documento
    ADD CONSTRAINT estados_documento_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_estados_factura
    ON public.estados_documento(factura_id);


ALTER TABLE IF EXISTS public.facturas
    ADD CONSTRAINT fk_facturas_sociedad FOREIGN KEY (sociedad_id)
    REFERENCES public.sociedades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_facturas_sociedad
    ON public.facturas(sociedad_id);


ALTER TABLE IF EXISTS public.facturas_contabilizacion
    ADD CONSTRAINT facturas_contabilizacion_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS facturas_contabilizacion_factura_id_key
    ON public.facturas_contabilizacion(factura_id);


ALTER TABLE IF EXISTS public.mensajes_hacienda
    ADD CONSTRAINT fk_mensajes_sociedad FOREIGN KEY (sociedad_id)
    REFERENCES public.sociedades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.mensajes_hacienda
    ADD CONSTRAINT fk_mensajes_factura FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_mensajes_sociedad
    ON public.mensajes_hacienda(sociedad_id);
CREATE INDEX IF NOT EXISTS idx_mensajes_factura
    ON public.mensajes_hacienda(factura_id);


ALTER TABLE IF EXISTS public.notas_credito
    ADD CONSTRAINT fk_notas_sociedad FOREIGN KEY (sociedad_id)
    REFERENCES public.sociedades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_sociedad
    ON public.notas_credito(sociedad_id);


ALTER TABLE IF EXISTS public.notas_credito
    ADD CONSTRAINT notas_credito_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notas_credito_factura
    ON public.notas_credito(factura_id);


ALTER TABLE IF EXISTS public.roles_permisos
    ADD CONSTRAINT roles_permisos_permiso_id_fkey FOREIGN KEY (permiso_id)
    REFERENCES public.permisos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.roles_permisos
    ADD CONSTRAINT roles_permisos_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_roles_permisos_rol
    ON public.roles_permisos(rol_id);


ALTER TABLE IF EXISTS public.tramites_pago
    ADD CONSTRAINT tramites_pago_sociedad_id_fkey FOREIGN KEY (sociedad_id)
    REFERENCES public.sociedades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_tramites_pago_sociedad
    ON public.tramites_pago(sociedad_id);


ALTER TABLE IF EXISTS public.tramites_pago_documentos
    ADD CONSTRAINT tramites_pago_documentos_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tramites_pago_docs_factura
    ON public.tramites_pago_documentos(factura_id);


ALTER TABLE IF EXISTS public.tramites_pago_documentos
    ADD CONSTRAINT tramites_pago_documentos_tramite_id_fkey FOREIGN KEY (tramite_id)
    REFERENCES public.tramites_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tramites_pago_docs_tramite
    ON public.tramites_pago_documentos(tramite_id);


ALTER TABLE IF EXISTS public.tramites_pago_historial
    ADD CONSTRAINT tramites_pago_historial_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tramites_pago_historial
    ADD CONSTRAINT tramites_pago_historial_tramite_id_fkey FOREIGN KEY (tramite_id)
    REFERENCES public.tramites_pago (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tramites_pago_historial_tramite
    ON public.tramites_pago_historial(tramite_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_rol_id
    ON public.usuarios(rol_id);


ALTER TABLE IF EXISTS public.versiones_documento
    ADD CONSTRAINT versiones_documento_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_versiones_factura
    ON public.versiones_documento(factura_id);

END;
